Beginner Tutorials
=========================
Deep Learning with PyTorch: A 60 Minute Blitz
1. What is Pytorch?
2. Autograd: automatic differentiation

Offical Tutorial: http://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#variable

In [1]:
from __future__ import print_function
import torch

## Tensors

In [2]:
#Construct a 5x3 matrix, uninitialized:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  4.6566e-10  0.0000e+00
 4.6566e-10  7.0065e-45  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  4.6566e-10  1.4056e+19
[torch.FloatTensor of size 5x3]



In [3]:
#Construct a randomly initialized matrix
x = torch.rand(5, 3)
print(x)


 0.8189  0.0683  0.1503
 0.7245  0.7786  0.0010
 0.3036  0.9990  0.9381
 0.7206  0.0548  0.0544
 0.7824  0.4603  0.7370
[torch.FloatTensor of size 5x3]



In [4]:
#Get its size
print(x.size())

torch.Size([5, 3])


## Operations

In [5]:
# 相加
y = torch.rand(5,3)
print(x + y)


 1.0584  0.1774  0.4190
 0.9472  0.7884  0.5139
 0.9094  1.1269  1.3849
 1.3752  0.1708  0.6746
 0.9727  1.3338  1.1383
[torch.FloatTensor of size 5x3]



In [6]:
# 相加
print(torch.add(x,y))


 1.0584  0.1774  0.4190
 0.9472  0.7884  0.5139
 0.9094  1.1269  1.3849
 1.3752  0.1708  0.6746
 0.9727  1.3338  1.1383
[torch.FloatTensor of size 5x3]



In [7]:
#giving an output tensor
result = torch.Tensor(5,3)
torch.add(x,y, out=result)
print(result)


 1.0584  0.1774  0.4190
 0.9472  0.7884  0.5139
 0.9094  1.1269  1.3849
 1.3752  0.1708  0.6746
 0.9727  1.3338  1.1383
[torch.FloatTensor of size 5x3]



In [8]:
# in-place
# adds x to y
# y被改變成原本的y+x 
y.add_(x)
print(y)


 1.0584  0.1774  0.4190
 0.9472  0.7884  0.5139
 0.9094  1.1269  1.3849
 1.3752  0.1708  0.6746
 0.9727  1.3338  1.1383
[torch.FloatTensor of size 5x3]



In [10]:
print(y[:, 0])


 1.0584
 0.9472
 0.9094
 1.3752
 0.9727
[torch.FloatTensor of size 5]



## Converting tensors to numpy array

In [19]:
a = torch.ones(5,2)
print(a)


 1  1
 1  1
 1  1
 1  1
 1  1
[torch.FloatTensor of size 5x2]



In [20]:
# torch 轉 numpy
b = a.numpy()
print(b)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [21]:
a.add_(1)
print(a)
print(b)


 2  2
 2  2
 2  2
 2  2
 2  2
[torch.FloatTensor of size 5x2]

[[ 2.  2.]
 [ 2.  2.]
 [ 2.  2.]
 [ 2.  2.]
 [ 2.  2.]]


## Converting numpy Array to torch Tensor

In [26]:
# numpy 轉 torch
import numpy as np
a = np.array([[1,3], [1,4]])
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[[2 4]
 [2 5]]

 2  4
 2  5
[torch.LongTensor of size 2x2]



In [18]:
# if you have nvidia GPU
# let us run this cell only if CUDA is available
# 判斷電腦是否支持GPU
torch.cuda.is_available()

False

torch的自動求導功能
===============================
- torch 和大部分框架一樣有自動求導功能，但對象不再是 torch.Tensor，而是 torch.autograd.Variable
- 本質上 Variable 和 Tensor 沒有什麼區別，不過Variable會放在一個計算圖裡面，可以進行前向傳播和反向傳播以及求導數
- grad 表示反向傳播的梯度

In [27]:
from torch.autograd import Variable

In [28]:
# requires_grad 表示是否對其求梯度，預設是false
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2 * x + y + 4

In [29]:
# 對X,Y分別求導數
z.backward()

In [30]:
# X,Y 的導數
print("dz/dx:{}".format(x.grad.data))
print("dz/dy:{}".format(y.grad.data))

dz/dx:
 2
[torch.FloatTensor of size 1]

dz/dy:
 1
[torch.FloatTensor of size 1]



神經網絡部分
========
- 所依賴的主要是 torch.nn 和 torch.nn.functional
- torch.nn裡面有所有神經網絡的層的操作，其用來建構網絡，只有執行一次網絡的運算才執行一次
- torch.nn.functional 表示的是直接對其做一次向前運算操作
- 官方文檔：http://pytorch.org/docs/master/nn.html

In [31]:
from torch import nn
import torch.nn.functional as f

In [32]:
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__() # 運行nn.module的初始化函數     
        # 可以添加各種網絡層
        self.convl = nn.Conv2d(3,10,3)   # 輸入為3張圖像，輸出為10張特徵圖，卷積核為3X3正方形
        # 具體每種層的參數可以再去查看文檔
        
    def forward(self, x):
        # 定義向前傳播
        out = self.convl(x)
        return out